[build]
  command = "pnpm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # Prevent Netlify npm install
  # Note: Do not put your actual environment values here
  # Define these in the Netlify UI instead

[functions]
  node_bundler = "esbuild"

# Ensure environment variables are passed to the build process
[context.production]
  environment = { NODE_ENV = "production" }

# Add redirect for SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 