[build]
  command = "pnpm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # Prevent Netlify npm install

[functions]
  node_bundler = "esbuild" 